package:
  name: pacflypy
  version: "{{ load_setup_py_data().get('version', '0.0.0') }}"

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - pacflypy

about:
  home: https://github.com/pacflypy/pacflypy
  license: MIT
  summary: "A pure python Allreound Module for may Actions"
