name: Build Package and Upload him

on:
    workflow_call:
        inputs:
            version:
                description: "Version to build"
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Setup SSH
            run: |
              sudo apt-get update -qq
              sudo apt-get install -y openssh-sftp-server gh python3 python3-venv make
              sudo rm -rf ${HOME}/.ssh
              mkdir -p ${HOME}/.ssh
              cat <<EOF > ${HOME}/.pypirc
              [pypi]
              username = __token__
              password = ${{ secrets.PYPI_TOKEN }}
              EOF
              echo ${{ secrets.PRIVATE_KEY }} > ${HOME}/.ssh/${{ secrets.PRIVATE_NAME }}
              chmod 600 ${HOME}/.ssh/${{ secrets.PRIVATE_NAME }}
              echo ${{ secrets.PUBLIC_KEY }} > ${HOME}/.ssh/${{ secrets.PUBLIC_NAME }}
              chmod 600 ${HOME}/.ssh/${{ secrets.PUBLIC_NAME }}
              export GH_TOKEN=${{ secrets.GH_TOKEN }}
              git remote set-url origin git@github.com:pacflypy/pacflypy.git
              python3 -m venv .venv
              source .venv/bin/activate
              pip install -U pip
              pip install build twine
              make 
              deactivate